const express = require('express');
const router = express.Router();
const issueController = require('../controllers/issue.controller');
const { authenticate } = require('../middleware/auth');
const { authorizeRoles } = require('../middleware/authorize');
const upload = require('../middleware/multer');
router.post('/create', authenticate, authorizeRoles('publisher', 'admin'), upload.none(), issueController.createIssue);
router.put('/update/:id', authenticate, authorizeRoles('publisher', 'admin'), issueController.updateIssue);
router.patch('/update-status/:id/publish', authenticate, authorizeRoles('publisher', 'admin'), issueController.publishIssue);
router.get('/', issueController.getIssues);
router.get('/latest', issueController.getLatestIssue);
router.get('/featured-manuscripts', issueController.getFeaturedManuscripts);
router.get('/slug/:slug', issueController.getIssueBySlug);
router.get('/:id', issueController.getIssueById);
router.patch('/:id/add-manuscript', authenticate, authorizeRoles('publisher', 'admin'), issueController.addManuscript);
router.patch('/:id/remove-manuscript', authenticate, authorizeRoles('publisher', 'admin'), issueController.removeManuscript);
router.patch('/:id/archive', authenticate, authorizeRoles('publisher', 'admin'), issueController.archiveIssue);
router.delete('/:id', authenticate, authorizeRoles('publisher', 'admin'), issueController.deleteIssue);

module.exports = router;
